### ISSUE TITLE
Return the "completeness" for every item within indicator_location_data.

### ISSUE THREAD

**Issue by rkrupinski** [unicef/etools-partner-reporting-portal#183] opened 2017-07-13 07:49 UTC
Need this for marking location tabs as complete / incomplete.

**Comment by chachra** [comment] 2017-07-13 17:46
@rkrupinski Isn't this a dupe of #156 already assigned to @lkolacz  ?

**Comment by rkrupinski** [comment] 2017-07-14 06:06
Yep, I guess. Deleting.

**Closed** 2017-07-14 06:06 UTC
