### ISSUE TITLE
Cannot make 'User Changes' to Django Admin

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#628] opened 2018-04-26 17:59 UTC
@maciej-jaworski @n1207n Getting errors if any changes are made and then I try to save. Switching partners, adding workspaces, subtracting clusters, etc are all return errors so cannot make any changes.

We believe the added password functionality might have caused this issue as it was working before.

![Screen Shot 2018-04-26 at 10.57.03 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f56b7191a379ef0c2e56415f4dbc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e54a53a1163e60e47f3e6e0a.png)

![Screen Shot 2018-04-26 at 11.03.26 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f56b7191a379ee0c2b52415d48bc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e54a53a11a3f61ef7f3f6e0a.png)

**Comment by n1207n** [comment] 2018-04-26 23:32
Locally, User admin seems to be fixed now, as I cannot reproduce the error anymore. I think Maciej pushed a fix shortly after this was introduced this morning.

Will test this out in staging soon with brand new user.

**Comment by n1207n** [comment] 2018-04-27 00:00
This is now fixed. Did a brand new user sign up via Active Directory in prp.tivixlabs.com. IMO user was able to associate role and partner and saved it just fine.

#623 issue is also fixed together.

**Closed** 2018-04-27 17:28 UTC
Labels: bug, delivered
