### ISSUE TITLE
Current Progress and Achieved not calculating properly

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#534] opened 2018-03-09 19:11 UTC
![Screen Shot 2018-03-09 at 2.06.43 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454fa6b7191a37af1122d4f5b5c5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29941c95df44be74f57a3123662ef712431.png)

![Screen Shot 2018-03-09 at 2.03.42 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454fa6b7191a37af112284f5b5d5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df44be74f57a3113663ee702431.png)

**Comment by momimomo** [comment] 2018-04-12 09:11
Calculation blueprints don't seem to be in frontend...
I think they can be found in factories.py @n1207n ?
the percentage seems to be randomly generated, so maybe it was left after some initial demo?
if it's not the case then I'll dig deeper.

**Comment by n1207n** [comment] 2018-04-12 18:19
For fake data, we do randomly generate progress and percentage values. That cluster reporting screenshot is an example of that.

However, IP reporting screenshot is from staging it seems, with real ProgrammeDocuments. I think we should examine those if they are also randomly generated. They should not.

**Comment by momimomo** [comment] 2018-04-17 12:34
Can't reproduce - neither on staging or locally I can't see or set any indicators in ip reporting under indicators tab. Please share what should be the combination of user / response plan / workspace to see some data.

**Comment by sethgold8** [comment] 2018-04-18 18:46
@momimomo on IP, if I enter indicator data, 'Achievement in reporting period' does not dynamically update. 

![Screen Shot 2018-04-18 at 11.42.16 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455fb6b7191a379ee0c2f53415e48bc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e54d52a3123367e377346e0a.png)

After Refresh it does

![Screen Shot 2018-04-18 at 11.41.39 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455fb6b7191a379ee0c2f50415c47bc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29b4bc259f349e54d52a3123f64e1763e6e0a.png)

But Total Cumulative Progress does not update

![Screen Shot 2018-04-18 at 11.42.54 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455fb6b7191a379ee0c2f53415a4abc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e54d52a3133e61ee7f336e0a.png)

**Comment by momimomo** [comment] 2018-04-25 08:00
Merged.

**Comment by sethgold8** [comment] 2018-04-25 20:11
worksgood :)

**Closed** 2018-04-25 20:11 UTC
Labels: bug, cluster reporting, delivered, ip reporting
