### ISSUE TITLE
Race condition in location-filter?

### ISSUE THREAD

**Issue by adamtlord** [unicef/etools-partner-reporting-portal#98] opened 2017-06-07 00:19 UTC
There seems to be some kind of race condition in location-filter.html that results in a call to the childLocations endpoint without a locationId:
`http://localhost:8080/api/core//children-location/`, which 404s

**Comment by adamtlord** [comment] 2017-06-07 00:34
I'm seeing this on the PD list page, btw

**Comment by rkrupinski** [comment] 2017-06-07 06:51
@adamtlord What branch?

**Comment by rkrupinski** [comment] 2017-06-07 06:54
I can only reproduce it in one scenario:

1) Run docker
2) Navigate to `localhost:8080`
3) Switch tabs
4) Save a file and let the app auto-refresh

**Comment by rkrupinski** [comment] 2017-06-07 08:08
Okay, here's the genesis of the problem:

1) Reducers can't return `undefined`, one can't initialize a field on the store with the value `undefined`.
2) Polymer change detection does not skip all falsy values, it only skips `undefined`.
3) We end up having `''` considered a valid value for `locationId`.
4) Somehow the order of execution when switching back to the `localhost` tab (Chrome optimizations FTW) exposes this.

Here's a fix: 4d88d98afa362b6a59e69d09975fef3299b96584

**Comment by rkrupinski** [comment] 2017-06-07 08:09
It turns out that the PD filter (indicators screen) suffers from the same issue.

**Comment by rkrupinski** [comment] 2017-06-07 09:01
Fix: faf628ee98ac6cb752caa1ba113735509ddeebb6

Also, @ErinOC , please take a look at:

https://github.com/unicef/etools-partner-reporting-portal/commit/faf628ee98ac6cb752caa1ba113735509ddeebb6#diff-b0c39de2b5cedce4df23b80f9959319dL26

The point of having the `value` prop is not to have to rely on `queryParams` within filter components. This makes them more generic/decoupled and easier to test in isolation.

**Comment by rkrupinski** [comment] 2017-06-07 09:07
One more bug (that's technically out of scope):

1a7c58adccc80c8a7d744d5966d578df360310c9

@ErinOC Not that Polymer does NOT support selector nesting. Think of it as the good old CSS + mixins (`@apply`).

**Closed** 2017-06-07 09:07 UTC
Labels: bug, help wanted

**Comment by ErinOC** [comment] 2017-06-07 18:40
@rkrupinski Thanks for catching that. I knew that nesting isn't supported; accidentally pasted the new style in the wrong spot.
