### ISSUE TITLE
Unable to send a message to IMO

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#932] opened 2018-09-28 14:06 UTC
Browser:Chrome 
workspace:Iraq 
dev.prp environment
Steps: 
- Login as an IMO. 
-Create a cluster activity indicator. 
-Adopt the same cluster indicator into Partner Activity. 
-Click Save. 
-Logout 
-Now Login as an IMO or Cluster member or Cluster Co-ordinator. 
-Go to the same partner activity indicator. 
-Click on Edit. 
-Add a location. 
-Click on "Send message to IMO'. 
-Add message. 
Click SAVE. 
Result: Error msg is displayed. "You do not have permission to perform this action.Tried with IMO, Cluster Member and Cluster Co-ordinator as well, same error msg appears.

**Comment by KKaselkar** [comment] 2018-09-28 14:07
![image](https://user-images.githubusercontent.com/32198614/46213321-433b9b00-c306-11e8-8841-39cc6e969e5d.png)

**Comment by KKaselkar** [comment] 2018-09-28 14:07
![image](https://user-images.githubusercontent.com/32198614/46213347-50588a00-c306-11e8-8eff-e91380e96daf.png)

**Comment by sethgold8** [comment] 2018-10-02 23:39
duplicate of #845 closing

**Closed by sethgold8** 2018-10-02 23:39 UTC
Labels: cluster reporting
