### ISSUE TITLE
Ratio and Percentage Calculation Method in IP PRP

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#921] opened 2018-09-19 13:51 UTC
dev.prp environment 
Iraq workspace
PD number : IRQ/PCA2018245/PD2018512-1
Ratio and Percentage calculation methods indicators do no show the accurate values on the page.

Ratio indicator displays values in percentage.

For ratio if user added 1/100 and 2 /1000 it should not be 3/1100
To make this calculation work correctly we will have common denominator which is a constant number so the calculation method for ratio is correct.

**Comment by KKaselkar** [comment] 2018-09-19 13:52
![image](https://user-images.githubusercontent.com/32198614/45757553-a6844980-bbf1-11e8-990e-089b5449013e.png)

**Comment by sethgold8** [comment] 2018-10-11 21:35
closing as this is a duplicate of #973

**Closed by sethgold8** 2018-10-11 21:35 UTC
Labels: bug, ip reporting
