### ISSUE TITLE
Incorrect Total Cumulative progress

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-partner-reporting-portal#972] opened 2018-10-10 19:00 UTC
I am testing here:
app/IRQ/ip-reporting/pd/1021/report/1425/view?page=1 

Partner: The human rights centre in Iraq
PD: IRQ/PCA2018259/PD2018482

It is HR2 (ind: 4 Perc Ind 1 Loc 2 Dis)

I submitted the report and I can see this:
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58b6fe776743c32000a1b8c2/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51fb2876ddb02def112d580c5e4bac41515d41fbff8e29a0a42062c80d55b98e30063e937f03a6aa8317b500bf23824e8cbebc884ec1ed3e37aa.PNG)

The total cumulative progress is incorrect. Based on my manual cals it should be 17.17%

**Comment by sethgold8** [comment] 2018-10-19 19:39
duplicate of #971

**Closed by sethgold8** 2018-10-19 19:39 UTC
Labels: ip reporting
