### ISSUE TITLE
Feature - A public API endpoint for Active response plan list

### ISSUE THREAD

**Issue by n1207n** [unicef/etools-partner-reporting-portal#287] opened 2017-09-05 20:28 UTC
For the incoming PMP<->PRP integration process, PRP needs to expose a new private API for PMP to consume regarding cluster indicator info.

This API endpoint will filter all ResponsePlan objects with today Date object, whose start and end date belong to the today in between.

**Comment by chachra** [comment] 2017-09-24 18:37
dupe of #286 way I solved it...  @robertavram

**Comment by robertavram** [comment] 2017-10-02 13:53
@chachra yep ... I think we can work with that one instead

**Closed** 2017-10-05 13:43 UTC
Labels: delivered
