### ISSUE TITLE
Cluster Reporting: Cluster Analysis tab

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#271] opened 2017-08-23 18:42 UTC
Specifications here: #185 

- [ ] API for cluster tab analysis

- [ ] Front end for cluster tab analysis

@rkrupinski @dfryta we are thinking that location/map filtering might require a manual apply filter to change calculations

**Comment by chachra** [comment] 2018-01-15 22:38
Dupe of new issues. Closing for now.

**Closed by chachra** 2018-01-15 22:38 UTC
