### ISSUE TITLE
A way to reconcile Reportable's recalculated total from its child Reportable instances

### ISSUE THREAD

**Issue by n1207n** [unicef/etools-partner-reporting-portal#356] opened 2017-10-12 02:05 UTC
Per our discussion, once the PD recalculation upon IndicatorBlueprint changes is done, the Reportable instance may need to adjust its total based on its parent-child relationship.

This may require the refactoring on post_save signal on IndicatorReport for calculating Reportable totals and some conditions to check its children for getting a correct total value from.

**Comment by chachra** [comment] 2017-10-12 05:16
dupe of #184

**Closed by chachra** 2017-10-12 05:16 UTC
