### ISSUE TITLE
Include a “demo indicator table” in the Calculation Method Tab

### ISSUE THREAD

**Issue by kasialanecka** [unicef/etools-partner-reporting-portal#432] opened 2018-01-08 11:32 UTC
The need to include a “demo indicator table” in the Calculation Method Tab. Using an indicator as an example, the demo indicator table will enable the IP to see how the change of the calculation method for the sample indicator impacts progress reported across locations and reporting periods. This could provide an initial response to the challenge of setting the calculation method in a screen that is separate to the data entry screen.

**Comment by chachra** [comment] 2018-02-12 23:48
dupe of #453

**Closed by chachra** 2018-02-12 23:48 UTC
Labels: change requests, ip reporting
