### ISSUE TITLE
Make dev setup work on ubuntu 16.04

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#717] opened 2018-06-05 17:59 UTC
Please setup a local VM, make dev. environment up on 16.04 ubuntu.

Might require upgrading Docker base images where appropriate. When done please make sure same also continues working on Mac.

"fab up" is the command that should work on both then.

waitforit, proxy and polymer serve should work fine.

**Comment by n1207n** [comment] 2018-06-05 19:05
Just to clarify, is dev environment still gonna be set up as docker-compose in Ubuntu?

**Comment by chachra** [comment] 2018-06-05 19:06
yep.

**Comment by n1207n** [comment] 2018-06-05 21:00
I updated README.md for Ubuntu 16.04 dev setup. I had to disable letsencrypt setup for proxy since our staging now uses AWS Route53 for SSL setup, and local env does not benefit from such setup.

For polymer, it should work as intended. If you ever get ENOSPC node.js error from `npm run dev` command, that means there is no disk space left :l This should only happen if you're running Ubuntu VM with less disk space allocated. Host OS should not have this issue unless docker filesystem is almost full of capacity.

I was able to run vagrant Ubuntu 16.04 with docker-compose running containers successfully.

Let me know if anything comes up.

**Comment by sethgold8** [comment] 2018-06-08 22:12
@robertavram can you set up prp environment in ubuntu according to readme file and see if polymer + django are working?

cc @n1207n

**Comment by domdinicola** [comment] 2018-06-12 20:14
Hi guys,

I cannot run fab up :(

probably a dependency library is missing.. can you please double check and support?

> 

  Could not resolve 'security.debian.org'
Fetched 9753 kB in 20s (470 kB/s)
Reading package lists...
W: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/InRelease  Could not resolve 'security.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libapt-inst2.0
The following NEW packages will be installed:
  apt-utils libapt-inst2.0
0 upgraded, 2 newly installed, 0 to remove and 1 not upgraded.
Need to get 602 kB of archives.
After this operation, 1607 kB of additional disk space will be used.
Get:1 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libapt-inst2.0 amd64 1.4.8 [192 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 apt-utils amd64 1.4.8 [410 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 602 kB in 6s (91.6 kB/s)
Selecting previously unselected package libapt-inst2.0:amd64.
(Reading database ... 7027 files and directories currently installed.)
Preparing to unpack .../libapt-inst2.0_1.4.8_amd64.deb ...
Unpacking libapt-inst2.0:amd64 (1.4.8) ...
Selecting previously unselected package apt-utils.
Preparing to unpack .../apt-utils_1.4.8_amd64.deb ...
Unpacking apt-utils (1.4.8) ...
Setting up libapt-inst2.0:amd64 (1.4.8) ...
Setting up apt-utils (1.4.8) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 build-essential : Depends: dpkg-dev (>= 1.17.11) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
ERROR: Service 'proxy' failed to build: The command '/bin/sh -c apt-get update &&     apt-get install -y --no-install-recommends apt-utils &&     apt-get install --assume-yes python-pip python-dev python-setuptools build-essential cron' returned a non-zero code: 100

Fatal error: local() encountered an error (return code 1) while executing 'docker-compose up --force-recreate --build'

Aborting.

>

**Comment by domdinicola** [comment] 2018-06-12 20:25
second time it did work... weird

**Comment by n1207n** [comment] 2018-06-12 20:29
@domdinicola,

It seemed that you had some sort of network issue when docker-compose ran apt-get commands:

```
W: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/InRelease Could not resolve 'security.debian.org'
```

When you tried second time, it may have pulled the apt-get dependencies correctly.

**Comment by robertavram** [comment] 2018-06-13 18:30
After a bit of debugging ... noticed what was causing polymer to fail on some Ubuntu systems:
https://stackoverflow.com/questions/22475849/node-js-error-enospc/32600959#32600959

https://github.com/facebook/jest/  issues/3254/

Played around with the docker-file and got it to work eventually...

**Closed** 2018-06-13 23:06 UTC
Labels: bug, delivered
